### ISSUE TITLE
Logically Wrong

### ISSUE THREAD

**Issue by ariG23498** [forkbomb-666/prolog_for_noobs#2]
https://github.com/forkbomb-666/prolog_for_noobs/blob/4464ad475b9678d99aa80cd52edfa50beceb4bb1/codes/dist0.pl#L19

Refering to the code, this cannot be broken to the code below, as this is an OR operation. This needs to be understood that for the broken code, it signifies that both together are rules given which is an AND operation.

**Comment by royarg02** [comment]
This is possible in prolog as it _is_ an OR operation.
The design of the prolog syntax makes the binding of different bodies to the same head of any rule associate them by an **OR** operation.
```prolog
odd(7).
even(10).
isNumber(X) :- odd(X).
isNumber(X) :- even(X).
```
Try querying the above knowledge base with `?- isNumber(7).`
The same behavior as that of `isNumber(X) :- odd(X) ; even(X)` is obtained.

**Comment by ariG23498** [comment]
But can you give me an example where any one of the rule will turn out to be false and then we can be sure. Here we know that both the statements are true hence won't matter.

**Comment by royarg02** [comment]
Both the conditions won't be true for the above query.
`even(7)` for the above script will return `false`.

**Comment by ariG23498** [comment]
Yes, okay.
Thanks :cake:
